### ISSUE TITLE
loo fails with error on a particular matrix

### ISSUE THREAD

**Issue by edbaskerville** [jgabry/loo#10]
I have a matrix—which I will happily send you—that causes loo to return an error:

```
> load('log_lik_mat.RData')
> dim(log_lik_mat)
[1]  100 3255
> loo(log_lik_mat, cores=1)
Error in if (sigma <= 0) return(rep(NaN, length(p))) : 
  missing value where TRUE/FALSE needed
```

The matrix contains no NaNs and no Infs but does contain a lot of zeros.

However, the following works fine:
```
> log_lik_mat <- matrix(0, nrow=100, ncol=3255)
> loo(log_lik_mat)
Computed from 100 by 3255 log-likelihood matrix

         Estimate  SE
elpd_loo      0.0 0.0
p_loo         0.0 0.0
looic         0.0 0.0

All Pareto k estimates OK (k < 0.5)> 
```

(Minor note: missing newline in output for successful result.)

**Comment by edbaskerville** [comment]
Just emailed you the .RData file.

**Comment by jgabry** [comment]
Thanks Ed, I got the email. That's really helpful. I'll take a look and see if I can figure out what's up. 

It shouldn't matter, but did you install from CRAN or GitHub?

**Comment by edbaskerville** [comment]
CRAN—so I haven't checked against the latest commit.

**Comment by jgabry** [comment]
Regarding the error, it's being triggered by computations on some of the non-zero columns. Zeros are still the problem, but it's some zeros that come from exponentiating and not zeros in the original matrix.

I implemented a simple fix that I think gets around the problem on the issue_10 branch (you can install it by running `devtools::install_github("jgabry/loo", ref = "issue_10")`). It shouldn't give you an error with that log-likelihood matrix anymore. (You will probably get some warnings about large k values, because for the columns that are all zeros k gets set to `Inf`. If k > 1 for any of the non-zero columns then that may signal other issues, but it might just be that all the k > 1 are from the zeros. You could check that pretty easily.) 

I'm curious, what kind of model and data are you working with that leads to a log-likelihood matrix like this?

**Comment by edbaskerville** [comment]
I almost sent you a description and Stan code for the model when I realized that I was spitting out probabilities rather than log-probabilities. (Never trust old code you wrote and never actually used.) The model is going to need some not-quite-0 and not-quite-1 upper and lower bounds for the probabilities for things to be OK—this is very far from convergence, of course, but those will still need to be there. (These are a bunch of Bernoulli variables with probabilities regressed on latent variables.)

But, theoretically, I suppose this kind of matrix could still appear, but probably only if someone was trying to systematically generate a weird model.

**Comment by jgabry** [comment]
Ok, well let me know if you get any errors if you try loo with the right log_lik matrix.

**Comment by jgabry** [comment]
I'm going to close this issue for now, but we can reopen it if necessary.
